name: gh-actions test
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo my secret is ${{ secrets.my_credential }} > secret_file

